### ISSUE TITLE
어플리케이션 배포

### ISSUE THREAD

**Issue by watanka** [watanka/langchain-youtube-video-summarizer#7]
## 목적
- [ ] 쿠버네티스 배포 전 도커-컴포즈 배포
- 클라우드를 사용한 서비스 배포
- [ ] 네이버 클라우드 사용 #15 
    - [ ] 쿠버네티스 사용 배포
### 배포 전에 확인해야하는 것
- [ ] 모델 서빙 최적화 #1 
- [ ] 악의적인 사용 방지를 위한 제한 조건 추가 #8 
- [ ] 유저 사용 기록에 대한 로깅 #4
